// react-event/src/App.js
import React, { Component } from 'react';
import './App.css';
import EventForm from './components/EventForm';
import EventList from './components/EventList';

class App extends Component {
  id = 1

  state = {
    events: [
      {
        id: 0,
        title: 'Example',
        description: 'Example'
      }
    ]
  }

  handleCreate = (event) => {
    const { events } = this.state;
    this.setState({
      events: events.concat({
        id: this.id++,
        ...event
      })
    });
  }

  render() {
    return (
      <div>
        <EventForm 
          onCreate={this.handleCreate}
        />
        <EventList events={this.state.events} />
      </div>
    );
  }
}

export default App;

// vue-event/src/App.vue
<template>
  <div>
    <EventForm v-on:onCreate="handleCreate" />
    <EventList v-bind:events="state.events" />
  </div>
</template>

<script>
import EventForm from './components/EventForm';
import EventList from './components/EventList';

export default {
  name: 'app',
  components: {
    EventForm,
    EventList
  },
  data() {
    return {
      id: 1,
      state: {
        events: [
          {
            id: 0,
            title: 'Example',
            description: 'Example'
          }
        ]
      }
    };
  },
  methods: {
    handleCreate(event) {
      const { events } = this.state;
      this.state.events.push({
          id: this.id++,
          ...event
        });
    }
  }
}
</script>

<style>
</style>
