// react-event/src/components/EventList.js
import React, { Component } from 'react';
import Event from './Event';

const EventList = (props) => {
    const { events } = props;
    const list = events.map(event => (
        <Event key={event.id} event={event} />
    ));
    
    return (
        <div>
            {list}
        </div>
    )
}

EventList.defaultProps = {
    events: []
}

export default EventList;

// vue-event/src/components/EventList.vue
<template>
    <div>
        <template v-for="event in events">
            <Event v-bind:key="event.id" v-bind:event="event" />
        </template>
    </div>
</template>
<script>
import Event from './Event';

export default {
    props: ['events'],
    components: {
        Event
    }
}
</script>
<style scoped>

</style>
