// vue-event/src/components/Event.vue
<template>
    <div class="event">
        <div><b>{{title}}</b></div>
        <div>{{description}}</div>
    </div>
</template>
<script>
export default {
    props: ['event'],
    data() {
        return {
            title: this.event.title,
            description: this.event.description
        };
    }
}
</script>
<style scoped>
.event {
    border: 1px solid black;
    padding: 8px;
    margin: 8px;
}
</style>

// react-event/src/components/Event.js
import React from 'react';
import './Event.css';

const Event = (props) => {
    const { title, description } = props.event;

    return (
        <div className="event">
            <div><b>{title}</b></div>
            <div>{description}</div>
        </div>
    );
}

Event.defaultProps = {
    event: {
        id: 1,
        title: 'Example',
        description: 'Example'
    }
}

export default Event;
